fix: Update redirect old url to new url
edificeio/blog pull request #49
Opened 2024-02-20 11:01 UTC by Romu-C

The goals is to remove the useNavigation from the react component which cause re-rendering all page when using useSearchParams.

2024-02-20 14:16 UTC, ccreusat requested changes

2024-02-20 14:16 UTC, ccreusat commented on frontend/src/routes/old-url/index.tsx
un meilleur nom que "old-url" stp 🤣 

`redirect` peut être..

2024-02-20 14:16 UTC, ccreusat commented on frontend/src/routes/old-url/index.tsx
@Romu-C 
reprendre correctement le code du hook complet 

```
const blog = matchPath("/view/:blogId", ngLocation);
      const post = matchPath("/detail/:blogId/:postId", ngLocation);

      const blogPath = `/id/${blog?.params.blogId}`;
      const postPath = `/id/${post?.params.blogId}/post/${post?.params.postId}`;

      if (blog) return redirect(blogPath);
      if (post) return redirect(postPath);
```

meilleure lisibilité, clean code 👍🏼

2024-02-20 14:17 UTC, ccreusat commented on frontend/src/routes/index.tsx
> +      // TODO add 404 page
ajouter la page dans cette PR stp, sinon c'est l'oublie assuré
ex: https://github.com/OPEN-ENT-NG/mindmap/blob/develop/frontend/src/routes/page-error/index.tsx

2024-02-20 14:18 UTC, Romu-C commented on frontend/src/routes/old-url/index.tsx
j'étais pas trop inspiré xD

2024-02-21 10:31 UTC, ccreusat approved these changes

2024-02-21 10:52 UTC, merged